#!/bin/bash

cd ~/.local/share
if [ -d "Bisq" ]; then
	zip -r bisqbackup.zip Bisq
	mv bisqbackup.zip ~
else
	echo "Dir '.local/share/Bisq' does not exist"
fi

cd ~
if [ -d ".bitcoin" ]; then
	cd .bitcoin
	if [ -f "wallet.dat" ]; then
		zip -r walldat.zip wallet.dat
		mv walldat.zip ~
	elif [ -d "wallets" ]; then
		zip -r walldat.zip wallets
		mv walldat.zip ~
	fi
else
	echo "Dir '.bitcoin' does not exist"
fi
cd ~
